# Base Ethical Contract v1.0
[contract]
name = "base_ethics"
version = "1.0.0"
description = "Foundational ethical guardrails"
audit_level = "full"

[rules]
no_harm = true
respect_privacy = true
truthfulness_required = true
user_consent_required = true
transparency_required = true

[memory]
consent_required = true
retention_limits = true
deletion_rights = true

[validation]
before_memory_storage = true
before_external_action = true
on_sensitive_topics = true
on_personal_information = true
before_decision_making = true

[audit]
log_all_decisions = true
require_justification = true
enable_trace_back = true
store_in_logbook = true

[consequences]
warn_user = true
block_action = true
escalate_to_human = true
log_violation = true
