[[keys]]
key_id = "ethos/2025-09-r1"
pubkey_hex = "ed25519:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
not_before = "2025-09-01T00:00:00Z"
not_after  = "2026-03-01T00:00:00Z"

[[keys]]
key_id = "ethos/2026-03-r1"
pubkey_hex = "ed25519:BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
not_before = "2026-02-01T00:00:00Z"
not_after  = "2026-09-01T00:00:00Z"

