name = "Nonviolence Protocol"
version = "1.0.0"
description = "Contract to prevent violent language and threats"

# Allow rules (whitelist) - these take precedence
[[rules]]
action = "say"
matches_any = ["kill for a slice", "kill for a pizza", "killing it", "kill time", "killer app", "killer deal"]
violation = "Safe idiom usage"
effect = "allow"
severity = "none"

# Violation rules - checked after allow rules
[[rules]]
action = "say"
contains_any = ["hurt", "harm", "attack", "kill"]
violation = "Personal threat or harm language detected"
violation_code = "harm_threat_personal"
action_suggestion = "Please avoid language that suggests harm to people"
severity = "high"

[[rules]]
action = "say"
contains_any = ["destroy", "annihilate", "demolish"]
violation = "Generic destructive language detected"
violation_code = "harm_language_generic"
action_suggestion = "Consider using more constructive language"
severity = "medium"

[[rules]]
action = "say"
contains_any = ["stab", "shoot", "punch"]
violation = "Violent tool or method suggested"
violation_code = "violent_suggestion"
action_suggestion = "Please avoid suggesting violent methods"
severity = "high"

[[rules]]
action = "say"
contains_any = ["deserved it", "had it coming"]
violation = "Justification of violence detected"
violation_code = "justification_of_violence"
action_suggestion = "Please avoid justifying harmful actions"
severity = "high"