name: CI

on:
  push:
    branches: [ main, config, develop ]
  pull_request:
    branches: [ main, config, develop ]

permissions:
  contents: read
  actions: write  # allow actions/cache to save new cache entries

jobs:
  build-and-test:
    name: Build & Test (workspace)
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry + git + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            synaptik-workspace/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Workspace build
        run: |
          cd synaptik-workspace
          cargo build --workspace --all-features --locked

      - name: Workspace tests
        run: |
          cd synaptik-workspace
          cargo test --workspace --all-features --locked --no-fail-fast

      - name: Build contracts crate for wasm32
        run: |
          cd synaptik-workspace
          cargo build -p contracts --target wasm32-unknown-unknown --locked --release
